name: custom_pointed_popup
description: Popup that can be shown on any targeted widget with customized pointed design.
version: 0.0.1
author: Dipak Shrestha<dipak.shrestha@eemc.edu.np>
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
